package com.colleen.s36349879.medtrack.data.tip

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single AI-generated medication tip saved for a patient
 * in the local Room database.
 *
 * This data class is annotated with [@Entity] to define it as a Room database table.
 * Each tip is linked to a specific patient and timestamped at the moment of insertion,
 * allowing the tip history to be displayed in chronological order.
 */
@Entity(tableName = "med_coach_tips")
data class MedCoachTip(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val patientId: String,
    val tipContent: String,      // The text generated by AI
    val timestamp: Long = System.currentTimeMillis() // To sort history by date
)
