package com.colleen.s36349879.medtrack.data.tip

import android.content.Context
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.colleen.s36349879.medtrack.data.medication.MedicationViewModel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.launch

/**
 * ViewModel responsible for managing AI-generated medication tip.
 *
 * This ViewModel communicates with [TipRepository] to save and retrieve
 * [MedCoachTip] records for a specific patient. Tips are generated by the
 * AI coach in [MedicationViewModel] and persisted here for future reference.
 *
 * @param context The application context used to initialize the repository.
 */
class TipViewModel (context: Context): ViewModel(){

    /**The repository used for all tip database operations.*/
    private val tipRepository: TipRepository = TipRepository(context)

    /**
     * Validates and saves an AI-generated tip for a specific patient.
     *
     * Silently returns without saving if either the patient ID or tip content
     * is blank, preventing empty records from being persisted.
     *
     * @param patientId The ID of the patient the tip was generated for.
     * @param content The AI-generated tip text to save.
     */
    fun saveGeneratedTip(patientId: String, content: String) {

        // Guard against saving empty or invalid tips
        if (content.isBlank() || patientId.isBlank()) return

        viewModelScope.launch {
            // Construct the tip object here so the UI only passes raw field values
            val newTip = MedCoachTip(
                patientId = patientId,
                tipContent = content
            )
            tipRepository.saveTip(newTip) // Persist the tip to the database
        }
    }

    /**
     * Retrieves the full tip history for a specific patient as a reactive stream.
     * The [Flow] will re-emit whenever the patient's tip history changes.
     *
     * @param patientId The ID of the patient whose tip history should be retrieved.
     * @return A [Flow] emitting the list of [MedCoachTip] records for the given patient.
     */
    fun getHistory(patientId: String): Flow<List<MedCoachTip>> {
        return tipRepository.getTipHistory(patientId)
    }

    /**
     * Factory class for creating instances of [TipViewModel].
     *
     * Required by [ViewModelProvider] to pass the [Context] dependency
     * into the ViewModel's constructor.
     *
     * @param context The context used to retrieve the application context.
     */
    class TipViewModelFactory(context: Context) : ViewModelProvider.Factory {
        private val context = context.applicationContext
        override fun <T : ViewModel> create(modelClass: Class<T>): T =
            TipViewModel(context) as T

    }
}