package com.colleen.s36349879.medtrack.ui.localization

import androidx.compose.runtime.staticCompositionLocalOf
import com.colleen.s36349879.medtrack.data.patient.AppLanguage

/**
 * Every piece of static UI text in the app, in one place, per [AppLanguage]. Read
 * through [LocalStrings] so any composable can do `LocalStrings.current.xyz` and get
 * the current patient's chosen language without an app restart (unlike Android's
 * built-in `strings.xml`/`values-<lang>` resource system, which only picks up a new
 * locale after the Activity is recreated).
 *
 * This does NOT translate user-submitted fact-check claims or the AI's response text
 * (that's controlled separately by [com.colleen.s36349879.medtrack.data.factcheck.FactCheckLanguage]
 * in the Fact-Check tab) — only the app's own chrome: nav, buttons, titles, labels, etc.
 */
data class Strings(
    // Common
    val ok: String,
    val cancel: String,
    val close: String,
    val save: String,
    val clear: String,
    val logout: String,
    val loading: String,
    val required: String,
    val confirmDate: String,
    val confirmTime: String,

    // Bottom navigation content descriptions
    val navHome: String,
    val navFactCheck: String,
    val navHealthAssistant: String,
    val navSymptoms: String,
    val navHistory: String,
    val navSettings: String,
    val navMedCoach: String,

    // Welcome screen
    val welcomeLogin: String,
    val welcomeClaimAccount: String,
    val welcomeSignUpPrompt: String,
    val welcomeDisclaimer: String,

    // Login screen
    val loginTitle: String,
    val loginPatientId: String,
    val loginPassword: String,
    val loginPatientIdRequired: String,
    val loginPasswordRequired: String,
    val loginInvalidCredentials: String,

    // Claim account screen
    val claimAccountTitle: String,
    val claimAccountPatientIdLabel: String,
    val claimAccountPatientIdRequired: String,
    val claimAccountPhoneLabel: String,
    val claimAccountPhoneRequired: String,
    val claimAccountNewPasswordLabel: String,
    val claimAccountSubmit: String,
    val claimAccountNoMatch: String,

    // Sign up screen
    val signUpTitle: String,
    val signUpFullName: String,
    val signUpFullNameRequired: String,
    val signUpPhone: String,
    val signUpPhoneRequired: String,
    val signUpPhoneMustStartWith04: String,
    val signUpPhoneMustBe10Digits: String,
    val signUpPhoneDigitsOnly: String,
    val signUpPhoneTaken: String,
    val signUpPassword: String,
    val signUpPasswordRequired: String,
    val signUpPasswordMinLength: String,
    val signUpPasswordNeedsLetter: String,
    val signUpPasswordNeedsNumber: String,
    val signUpConfirmPassword: String,
    val signUpConfirmPasswordRequired: String,
    val signUpPasswordsDontMatch: String,
    val signUpAge: String,
    val signUpAgeInvalid: String,
    val signUpLanguage: String,
    val signUpButton: String,
    val signUpAccountCreated: String,
    val signUpAlreadyHaveAccount: String,

    // Home screen
    val homeGreeting: String,
    val homeIdLabel: String,
    val homeMedsTakenSummary: String,
    val homeTodaysMedications: String,
    val homeNoMedications: String,
    val homeAddMedication: String,
    val homeDosageLabel: String,
    val homeFrequencyLabel: String,
    val homeTimeLabel: String,

    // Add medication screen
    val addMedicationTitle: String,
    val addMedicationNameLabel: String,
    val addMedicationNameRequired: String,
    val addMedicationDosageLabel: String,
    val addMedicationDosageRequired: String,
    val addMedicationDosageInvalid: String,
    val addMedicationFrequencyLabel: String,
    val addMedicationFrequencyRequired: String,
    val addMedicationNoTimeSelected: String,
    val addMedicationTypeLabel: String,
    val addMedicationTypeRequired: String,
    val addMedicationNotesLabel: String,
    val addMedicationSaved: String,

    // Symptoms screen
    val symptomsTitle: String,
    val symptomsCategoryLabel: String,
    val symptomsCategoryRequired: String,
    val symptomsSeverityLabel: String,
    val symptomsSeverityRangeError: String,
    val symptomsNotesLabel: String,
    val symptomsWhenOccurred: String,
    val symptomsSelectDate: String,
    val symptomsSelectTime: String,
    val symptomsDateRequired: String,
    val symptomsTimeRequired: String,
    val symptomsSaveButton: String,
    val symptomsSavedMessage: String,
    val symptomsHistoryTitle: String,
    val symptomsNoneLogged: String,
    val symptomsDateTimeLabel: String,
    val symptomsNotesPrefix: String,
    val symptomsMedicineAllergiesLabel: String,
    val symptomsMedicineAllergiesHint: String,
    val symptomsMedicineAllergiesSave: String,
    val severityMild: String,
    val severityModerate: String,
    val severityHigh: String,
    val severityUnknown: String,

    // Fact-Check screen
    val factCheckTitle: String,
    val factCheckSubtitle: String,
    val factCheckLanguageLabel: String,
    val factCheckClaimLabel: String,
    val factCheckClaimPlaceholder: String,
    val factCheckSubmit: String,
    val factCheckInstantMatch: String,
    val factCheckNoOfficialSource: String,
    val factCheckEvidenceSourceLabel: String,
    val factCheckEvidenceSourcesLabel: String,
    val factCheckViewSource: String,
    val factCheckFlagVerdict: String,
    val factCheckFlagged: String,
    val factCheckEmptyClaimError: String,
    val factCheckServiceError: String,
    val factCheckVoiceUnavailable: String,
    val factCheckAllergyWarning: String,
    val factCheckInteractionUnavailable: String,
    val verdictTrue: String,
    val verdictFalse: String,
    val verdictMisleading: String,
    val verdictUnverified: String,

    // Health Assistant screen
    val healthAssistantTitle: String,
    val healthAssistantSubtitle: String,
    val healthAssistantSymptomsLabel: String,
    val healthAssistantBloodPressureLabel: String,
    val healthAssistantTemperatureLabel: String,
    val healthAssistantSubmit: String,
    val healthAssistantFlagResponse: String,
    val healthAssistantFlagged: String,

    // MedCoach screen
    val medCoachTitle: String,
    val medCoachSubtitle: String,
    val medCoachSearchLabel: String,
    val medCoachSearchPlaceholder: String,
    val medCoachGetTip: String,
    val medCoachThinking: String,
    val medCoachViewHistory: String,
    val medCoachHistoryTitle: String,
    val medCoachNoHistory: String,
    val medCoachFdaLabelInfo: String,
    val medCoachPurpose: String,
    val medCoachWarnings: String,
    val medCoachAllergyWarning: String,
    val medCoachDosageAdmin: String,
    val medCoachIndications: String,
    val readMore: String,
    val showLess: String,

    // Settings screen
    val settingsTitle: String,
    val settingsAccountSection: String,
    val settingsNameLabel: String,
    val settingsPhoneLabel: String,
    val settingsPatientIdLabel: String,
    val settingsAgeLabel: String,
    val settingsAgeFieldLabel: String,
    val settingsAgeNotSet: String,
    val settingsAgeSave: String,
    val settingsLanguageSection: String,
    val settingsFontSizeSection: String,
    val settingsFontSizeDefault: String,
    val settingsFontSizeLarge: String,
    val settingsFontSizeExtraLarge: String,
    val settingsClinicianLogin: String,
    val settingsPreferencesSaved: String,

    // History screen
    val historyTitle: String,
    val historySubtitle: String,
    val historyEmpty: String,
    val historyOriginalMessageLabel: String,
    val historyResponseLabel: String,
    val historySourcesLabel: String
)

private val EnglishStrings = Strings(
    ok = "OK", cancel = "Cancel", close = "Close", save = "Save", clear = "Clear",
    logout = "Logout", loading = "Loading…", required = "required",
    confirmDate = "Confirm Date", confirmTime = "Confirm Time",

    navHome = "Home", navFactCheck = "Fact-Check", navHealthAssistant = "Health Assistant",
    navSymptoms = "Symptoms", navHistory = "History", navSettings = "Settings", navMedCoach = "MedCoach",

    welcomeLogin = "Login", welcomeClaimAccount = "Existing Patient? Claim Account",
    welcomeSignUpPrompt = "Don't have an account? Sign Up",
    welcomeDisclaimer = "*This app is for tracking purposes only and does not replace professional medical advice*",

    loginTitle = "Login", loginPatientId = "Patient ID", loginPassword = "Password",
    loginPatientIdRequired = "Patient Id is required", loginPasswordRequired = "Password is required",
    loginInvalidCredentials = "Invalid Patient ID or Password",

    claimAccountTitle = "Claim Account", claimAccountPatientIdLabel = "Patient ID (e.g. P1001)",
    claimAccountPatientIdRequired = "Patient ID is required", claimAccountPhoneLabel = "Phone Number",
    claimAccountPhoneRequired = "Phone Number is required", claimAccountNewPasswordLabel = "Set New Password",
    claimAccountSubmit = "Set Password & Claim",
    claimAccountNoMatch = "No matching Patient ID and Phone Number found.",

    signUpTitle = "Sign Up", signUpFullName = "Full Name (required)",
    signUpFullNameRequired = "Full Name is required", signUpPhone = "Phone Number (required)",
    signUpPhoneRequired = "Phone number is required", signUpPhoneMustStartWith04 = "Must start with 04",
    signUpPhoneMustBe10Digits = "Must be exactly 10 digits", signUpPhoneDigitsOnly = "Must contain only digits",
    signUpPhoneTaken = "This phone number is already registered", signUpPassword = "Password (required)",
    signUpPasswordRequired = "Password is required", signUpPasswordMinLength = "Must be at least 8 characters",
    signUpPasswordNeedsLetter = "Must contain at least one letter", signUpPasswordNeedsNumber = "Must contain at least one number",
    signUpConfirmPassword = "Confirm Password", signUpConfirmPasswordRequired = "Please confirm your password",
    signUpPasswordsDontMatch = "Passwords don't match", signUpAge = "Age (optional)",
    signUpAgeInvalid = "Enter a valid age (0-120)", signUpLanguage = "Preferred Language",
    signUpButton = "Sign Up", signUpAccountCreated = "Account %s Created!",
    signUpAlreadyHaveAccount = "Already have an account? Login",

    homeGreeting = "Hello, %s", homeIdLabel = "ID: %s",
    homeMedsTakenSummary = "%d of %d medications taken today", homeTodaysMedications = "Today's Medications",
    homeNoMedications = "No medications scheduled.", homeAddMedication = "Add Medications",
    homeDosageLabel = "Dosage: %s", homeFrequencyLabel = "Frequency: %s", homeTimeLabel = "Time: %s",

    addMedicationTitle = "Add Medication", addMedicationNameLabel = "Medication Name (required)",
    addMedicationNameRequired = "Medication name is required", addMedicationDosageLabel = "Dosage (required, e.g., “250mg”)",
    addMedicationDosageRequired = "Dosage is required", addMedicationDosageInvalid = "Invalid format. Use e.g., 500mg, 10ml, 1.5g",
    addMedicationFrequencyLabel = "Frequency (required)", addMedicationFrequencyRequired = "Frequency is required",
    addMedicationNoTimeSelected = "No time selected.", addMedicationTypeLabel = "Medication Type (required)",
    addMedicationTypeRequired = "Medication type is required", addMedicationNotesLabel = "Notes (optional)",
    addMedicationSaved = "Medication saved successfully!",

    symptomsTitle = "Log Symptoms", symptomsCategoryLabel = "Symptom Category",
    symptomsCategoryRequired = "Symptom category is required", symptomsSeverityLabel = "Severity: %d (%s)",
    symptomsSeverityRangeError = "Severity must be between 1 and 10", symptomsNotesLabel = "Additional Notes (optional)",
    symptomsWhenOccurred = "When did it occur?", symptomsSelectDate = "Select Date (required)",
    symptomsSelectTime = "Select Time (required)", symptomsDateRequired = "Date is required",
    symptomsTimeRequired = "Time is required", symptomsSaveButton = "Save Symptom",
    symptomsSavedMessage = "Symptom logged successfully", symptomsHistoryTitle = "Symptom History",
    symptomsNoneLogged = "No symptoms logged yet.", symptomsDateTimeLabel = "Date/Time: %s",
    symptomsNotesPrefix = "Notes: %s",
    symptomsMedicineAllergiesLabel = "Medicine allergies",
    symptomsMedicineAllergiesHint = "Enter medicine names separated by commas. This is saved to your patient profile.",
    symptomsMedicineAllergiesSave = "Save Allergies",
    severityMild = "Mild", severityModerate = "Moderate", severityHigh = "Severe", severityUnknown = "Unknown",

    factCheckTitle = "Fact-Check",
    factCheckSubtitle = "Paste a forwarded message or type a health claim to verify it against trusted sources.",
    factCheckLanguageLabel = "Language", factCheckClaimLabel = "Health claim",
    factCheckClaimPlaceholder = "e.g. \"5G towers spread COVID-19\"", factCheckSubmit = "Check this claim",
    factCheckInstantMatch = "Instant match (local cache)",
    factCheckNoOfficialSource = "⚠ No reliable Malaysian government source was found for this claim — this result is based on general web sources instead.",
    factCheckEvidenceSourceLabel = "Evidence Source:", factCheckEvidenceSourcesLabel = "Evidence Sources:",
    factCheckViewSource = "View official source", factCheckFlagVerdict = "Flag this verdict",
    factCheckFlagged = "Sent to doctor review", factCheckEmptyClaimError = "Please enter a claim to check.",
    factCheckServiceError = "Couldn't reach the verification service. Please check your connection and try again.",
    factCheckVoiceUnavailable = "Voice input isn't available on this device.",
    factCheckAllergyWarning = "⚠ Allergy Warning: This medicine matches a medicine you have recorded as an allergy.",
    factCheckInteractionUnavailable = "Medication interaction check is not enabled because no verified interaction source is configured. No interaction claim has been inferred.",
    verdictTrue = "TRUE", verdictFalse = "FALSE", verdictMisleading = "MISLEADING", verdictUnverified = "UNVERIFIED",

    healthAssistantTitle = "Health Assistant",
    healthAssistantSubtitle = "General informational guidance only — not a diagnosis.",
    healthAssistantSymptomsLabel = "Symptoms", healthAssistantBloodPressureLabel = "Blood pressure",
    healthAssistantTemperatureLabel = "Temperature", healthAssistantSubmit = "Get guidance",
    healthAssistantFlagResponse = "Flag this response", healthAssistantFlagged = "Sent to doctor review",

    medCoachTitle = "MedCoach", medCoachSubtitle = "FDA Drug Information Lookup",
    medCoachSearchLabel = "Search Medication", medCoachSearchPlaceholder = "Enter Drug Name (e.g. Panadol)",
    medCoachGetTip = "Get Personalised AI Tip", medCoachThinking = "Coach is thinking...",
    medCoachViewHistory = "View History", medCoachHistoryTitle = "Recent AI Tips",
    medCoachNoHistory = "No history found.",
    medCoachFdaLabelInfo = "FDA Official Label Info", medCoachPurpose = "Purpose",
    medCoachWarnings = "Important Warnings", medCoachAllergyWarning = "⚠ Allergy Warning: A medicine in your intake records matches a recorded allergy.", medCoachDosageAdmin = "Dosage & Administration",
    medCoachIndications = "Indications & Usage", readMore = "Read More...", showLess = "Show Less",

    settingsTitle = "Account Settings", settingsAccountSection = "Account", settingsNameLabel = "Name: %s",
    settingsPhoneLabel = "Phone: %s", settingsPatientIdLabel = "Patient ID: %s", settingsAgeLabel = "Age: %s",
    settingsAgeFieldLabel = "Age", settingsAgeNotSet = "Not set", settingsAgeSave = "Save Age", settingsLanguageSection = "Language",
    settingsFontSizeSection = "Font Size", settingsFontSizeDefault = "Default", settingsFontSizeLarge = "Large",
    settingsFontSizeExtraLarge = "Extra Large", settingsClinicianLogin = "Clinician Login",
    settingsPreferencesSaved = "Preferences saved",

    historyTitle = "History", historySubtitle = "Your past fact-check submissions.",
    historyEmpty = "No fact-checks yet. Results you check will appear here.",
    historyOriginalMessageLabel = "Original message", historyResponseLabel = "Response",
    historySourcesLabel = "Sources"
)

private val ChineseStrings = Strings(
    ok = "确定", cancel = "取消", close = "关闭", save = "保存", clear = "清除",
    logout = "登出", loading = "加载中…", required = "必填",
    confirmDate = "确认日期", confirmTime = "确认时间",

    navHome = "主页", navFactCheck = "事实查核", navHealthAssistant = "健康助手",
    navSymptoms = "症状", navHistory = "历史记录", navSettings = "设置", navMedCoach = "用药教练",

    welcomeLogin = "登录", welcomeClaimAccount = "已有账户？认领账户",
    welcomeSignUpPrompt = "还没有账户？注册",
    welcomeDisclaimer = "*本应用仅用于记录用途，不能替代专业医疗建议*",

    loginTitle = "登录", loginPatientId = "患者编号", loginPassword = "密码",
    loginPatientIdRequired = "请输入患者编号", loginPasswordRequired = "请输入密码",
    loginInvalidCredentials = "患者编号或密码无效",

    claimAccountTitle = "认领账户", claimAccountPatientIdLabel = "患者编号（例如 P1001）",
    claimAccountPatientIdRequired = "请输入患者编号", claimAccountPhoneLabel = "电话号码",
    claimAccountPhoneRequired = "请输入电话号码", claimAccountNewPasswordLabel = "设置新密码",
    claimAccountSubmit = "设置密码并认领",
    claimAccountNoMatch = "找不到匹配的患者编号和电话号码。",

    signUpTitle = "注册", signUpFullName = "姓名（必填）",
    signUpFullNameRequired = "请输入姓名", signUpPhone = "电话号码（必填）",
    signUpPhoneRequired = "请输入电话号码", signUpPhoneMustStartWith04 = "必须以 04 开头",
    signUpPhoneMustBe10Digits = "必须为 10 位数字", signUpPhoneDigitsOnly = "只能包含数字",
    signUpPhoneTaken = "该电话号码已被注册", signUpPassword = "密码（必填）",
    signUpPasswordRequired = "请输入密码", signUpPasswordMinLength = "至少需要 8 个字符",
    signUpPasswordNeedsLetter = "必须包含至少一个字母", signUpPasswordNeedsNumber = "必须包含至少一个数字",
    signUpConfirmPassword = "确认密码", signUpConfirmPasswordRequired = "请确认密码",
    signUpPasswordsDontMatch = "两次输入的密码不一致", signUpAge = "年龄（选填）",
    signUpAgeInvalid = "请输入有效年龄（0-120）", signUpLanguage = "偏好语言",
    signUpButton = "注册", signUpAccountCreated = "账户 %s 已创建！",
    signUpAlreadyHaveAccount = "已有账户？登录",

    homeGreeting = "您好，%s", homeIdLabel = "编号：%s",
    homeMedsTakenSummary = "今日已服用 %d / %d 种药物", homeTodaysMedications = "今日用药",
    homeNoMedications = "暂无安排的药物。", homeAddMedication = "添加药物",
    homeDosageLabel = "剂量：%s", homeFrequencyLabel = "频率：%s", homeTimeLabel = "时间：%s",

    addMedicationTitle = "添加药物", addMedicationNameLabel = "药物名称（必填）",
    addMedicationNameRequired = "请输入药物名称", addMedicationDosageLabel = "剂量（必填，例如“250mg”）",
    addMedicationDosageRequired = "请输入剂量", addMedicationDosageInvalid = "格式无效，例如：500mg、10ml、1.5g",
    addMedicationFrequencyLabel = "频率（必填）", addMedicationFrequencyRequired = "请选择频率",
    addMedicationNoTimeSelected = "尚未选择时间。", addMedicationTypeLabel = "药物类型（必填）",
    addMedicationTypeRequired = "请选择药物类型", addMedicationNotesLabel = "备注（选填）",
    addMedicationSaved = "药物保存成功！",

    symptomsTitle = "记录症状", symptomsCategoryLabel = "症状类别",
    symptomsCategoryRequired = "请选择症状类别", symptomsSeverityLabel = "严重程度：%d（%s）",
    symptomsSeverityRangeError = "严重程度必须介于 1 到 10 之间", symptomsNotesLabel = "补充说明（选填）",
    symptomsWhenOccurred = "何时发生？", symptomsSelectDate = "选择日期（必填）",
    symptomsSelectTime = "选择时间（必填）", symptomsDateRequired = "请选择日期",
    symptomsTimeRequired = "请选择时间", symptomsSaveButton = "保存症状",
    symptomsSavedMessage = "症状记录成功", symptomsHistoryTitle = "症状历史",
    symptomsNoneLogged = "尚未记录任何症状。", symptomsDateTimeLabel = "日期/时间：%s",
    symptomsNotesPrefix = "备注：%s",
    symptomsMedicineAllergiesLabel = "药物过敏",
    symptomsMedicineAllergiesHint = "请输入药物名称，用逗号分隔。此信息会保存到您的患者资料。",
    symptomsMedicineAllergiesSave = "保存过敏药物",
    severityMild = "轻微", severityModerate = "中度", severityHigh = "严重", severityUnknown = "未知",

    factCheckTitle = "事实查核",
    factCheckSubtitle = "粘贴转发的消息或输入健康相关说法，以对照可信来源进行核实。",
    factCheckLanguageLabel = "语言", factCheckClaimLabel = "健康说法",
    factCheckClaimPlaceholder = "例如：“5G 信号塔传播 COVID-19”", factCheckSubmit = "核实此说法",
    factCheckInstantMatch = "即时匹配（本地缓存）",
    factCheckNoOfficialSource = "⚠ 未找到可靠的马来西亚政府来源 — 此结果基于一般网络来源。",
    factCheckEvidenceSourceLabel = "证据来源：", factCheckEvidenceSourcesLabel = "证据来源：",
    factCheckViewSource = "查看官方来源", factCheckFlagVerdict = "标记此结果",
    factCheckFlagged = "已提交医生审核", factCheckEmptyClaimError = "请输入需要核实的说法。",
    factCheckServiceError = "无法连接验证服务，请检查网络连接后重试。",
    factCheckVoiceUnavailable = "此设备不支持语音输入。",
    factCheckAllergyWarning = "⚠ 过敏警告：此药物与您记录的药物过敏相符。",
    factCheckInteractionUnavailable = "由于尚未配置经过验证的药物相互作用来源，暂无法进行药物相互作用检查。系统不会推测相互作用。",
    verdictTrue = "真实", verdictFalse = "虚假", verdictMisleading = "误导性", verdictUnverified = "未经证实",

    healthAssistantTitle = "健康助手",
    healthAssistantSubtitle = "仅提供一般资讯指引 — 并非诊断。",
    healthAssistantSymptomsLabel = "症状", healthAssistantBloodPressureLabel = "血压",
    healthAssistantTemperatureLabel = "体温", healthAssistantSubmit = "获取建议",
    healthAssistantFlagResponse = "标记此回应", healthAssistantFlagged = "已提交医生审核",

    medCoachTitle = "用药教练", medCoachSubtitle = "FDA 药物资讯查询",
    medCoachSearchLabel = "搜索药物", medCoachSearchPlaceholder = "输入药物名称（例如 Panadol）",
    medCoachGetTip = "获取个性化AI建议", medCoachThinking = "教练思考中...",
    medCoachViewHistory = "查看历史记录", medCoachHistoryTitle = "最近的AI建议",
    medCoachNoHistory = "暂无历史记录。",
    medCoachFdaLabelInfo = "FDA官方标签信息", medCoachPurpose = "用途",
    medCoachWarnings = "重要警告", medCoachAllergyWarning = "⚠ 过敏警告：您的用药记录中有药物与已记录的过敏药物相符。", medCoachDosageAdmin = "剂量与用法",
    medCoachIndications = "适应症与用法", readMore = "阅读更多...", showLess = "收起",

    settingsTitle = "账户设置", settingsAccountSection = "账户", settingsNameLabel = "姓名：%s",
    settingsPhoneLabel = "电话：%s", settingsPatientIdLabel = "患者编号：%s", settingsAgeLabel = "年龄：%s",
    settingsAgeFieldLabel = "年龄", settingsAgeNotSet = "未设置", settingsAgeSave = "保存年龄", settingsLanguageSection = "语言",
    settingsFontSizeSection = "字体大小", settingsFontSizeDefault = "默认", settingsFontSizeLarge = "大",
    settingsFontSizeExtraLarge = "特大", settingsClinicianLogin = "临床医生登录",
    settingsPreferencesSaved = "偏好设置已保存",

    historyTitle = "历史记录", historySubtitle = "您过往的事实查核记录。",
    historyEmpty = "暂无事实查核记录。您核实过的结果将显示在这里。",
    historyOriginalMessageLabel = "原始消息", historyResponseLabel = "查核结果",
    historySourcesLabel = "来源"
)

private val BahasaMalaysiaStrings = Strings(
    ok = "OK", cancel = "Batal", close = "Tutup", save = "Simpan", clear = "Kosongkan",
    logout = "Log Keluar", loading = "Memuatkan…", required = "diperlukan",
    confirmDate = "Sahkan Tarikh", confirmTime = "Sahkan Masa",

    navHome = "Utama", navFactCheck = "Semak Fakta", navHealthAssistant = "Pembantu Kesihatan",
    navSymptoms = "Gejala", navHistory = "Sejarah", navSettings = "Tetapan", navMedCoach = "MedCoach",

    welcomeLogin = "Log Masuk", welcomeClaimAccount = "Pesakit Sedia Ada? Tuntut Akaun",
    welcomeSignUpPrompt = "Tiada akaun? Daftar",
    welcomeDisclaimer = "*Aplikasi ini hanya untuk tujuan penjejakan dan tidak menggantikan nasihat perubatan profesional*",

    loginTitle = "Log Masuk", loginPatientId = "ID Pesakit", loginPassword = "Kata Laluan",
    loginPatientIdRequired = "ID Pesakit diperlukan", loginPasswordRequired = "Kata laluan diperlukan",
    loginInvalidCredentials = "ID Pesakit atau Kata Laluan tidak sah",

    claimAccountTitle = "Tuntut Akaun", claimAccountPatientIdLabel = "ID Pesakit (cth. P1001)",
    claimAccountPatientIdRequired = "ID Pesakit diperlukan", claimAccountPhoneLabel = "Nombor Telefon",
    claimAccountPhoneRequired = "Nombor telefon diperlukan", claimAccountNewPasswordLabel = "Tetapkan Kata Laluan Baharu",
    claimAccountSubmit = "Tetapkan Kata Laluan & Tuntut",
    claimAccountNoMatch = "Tiada padanan ID Pesakit dan Nombor Telefon ditemui.",

    signUpTitle = "Daftar", signUpFullName = "Nama Penuh (diperlukan)",
    signUpFullNameRequired = "Nama Penuh diperlukan", signUpPhone = "Nombor Telefon (diperlukan)",
    signUpPhoneRequired = "Nombor telefon diperlukan", signUpPhoneMustStartWith04 = "Mesti bermula dengan 04",
    signUpPhoneMustBe10Digits = "Mesti tepat 10 digit", signUpPhoneDigitsOnly = "Hanya boleh mengandungi digit",
    signUpPhoneTaken = "Nombor telefon ini sudah didaftarkan", signUpPassword = "Kata Laluan (diperlukan)",
    signUpPasswordRequired = "Kata laluan diperlukan", signUpPasswordMinLength = "Mesti sekurang-kurangnya 8 aksara",
    signUpPasswordNeedsLetter = "Mesti mengandungi sekurang-kurangnya satu huruf", signUpPasswordNeedsNumber = "Mesti mengandungi sekurang-kurangnya satu nombor",
    signUpConfirmPassword = "Sahkan Kata Laluan", signUpConfirmPasswordRequired = "Sila sahkan kata laluan anda",
    signUpPasswordsDontMatch = "Kata laluan tidak sepadan", signUpAge = "Umur (pilihan)",
    signUpAgeInvalid = "Masukkan umur yang sah (0-120)", signUpLanguage = "Bahasa Pilihan",
    signUpButton = "Daftar", signUpAccountCreated = "Akaun %s Berjaya Dicipta!",
    signUpAlreadyHaveAccount = "Sudah mempunyai akaun? Log Masuk",

    homeGreeting = "Hai, %s", homeIdLabel = "ID: %s",
    homeMedsTakenSummary = "%d daripada %d ubat diambil hari ini", homeTodaysMedications = "Ubat Hari Ini",
    homeNoMedications = "Tiada ubat dijadualkan.", homeAddMedication = "Tambah Ubat",
    homeDosageLabel = "Dos: %s", homeFrequencyLabel = "Kekerapan: %s", homeTimeLabel = "Masa: %s",

    addMedicationTitle = "Tambah Ubat", addMedicationNameLabel = "Nama Ubat (diperlukan)",
    addMedicationNameRequired = "Nama ubat diperlukan", addMedicationDosageLabel = "Dos (diperlukan, cth., “250mg”)",
    addMedicationDosageRequired = "Dos diperlukan", addMedicationDosageInvalid = "Format tidak sah. Gunakan cth., 500mg, 10ml, 1.5g",
    addMedicationFrequencyLabel = "Kekerapan (diperlukan)", addMedicationFrequencyRequired = "Kekerapan diperlukan",
    addMedicationNoTimeSelected = "Tiada masa dipilih.", addMedicationTypeLabel = "Jenis Ubat (diperlukan)",
    addMedicationTypeRequired = "Jenis ubat diperlukan", addMedicationNotesLabel = "Nota (pilihan)",
    addMedicationSaved = "Ubat berjaya disimpan!",

    symptomsTitle = "Log Gejala", symptomsCategoryLabel = "Kategori Gejala",
    symptomsCategoryRequired = "Kategori gejala diperlukan", symptomsSeverityLabel = "Keterukan: %d (%s)",
    symptomsSeverityRangeError = "Keterukan mesti antara 1 dan 10", symptomsNotesLabel = "Nota Tambahan (pilihan)",
    symptomsWhenOccurred = "Bila ia berlaku?", symptomsSelectDate = "Pilih Tarikh (diperlukan)",
    symptomsSelectTime = "Pilih Masa (diperlukan)", symptomsDateRequired = "Tarikh diperlukan",
    symptomsTimeRequired = "Masa diperlukan", symptomsSaveButton = "Simpan Gejala",
    symptomsSavedMessage = "Gejala berjaya dilog", symptomsHistoryTitle = "Sejarah Gejala",
    symptomsNoneLogged = "Belum ada gejala dilog.", symptomsDateTimeLabel = "Tarikh/Masa: %s",
    symptomsNotesPrefix = "Nota: %s",
    symptomsMedicineAllergiesLabel = "Alahan ubat",
    symptomsMedicineAllergiesHint = "Masukkan nama ubat dipisahkan dengan koma. Maklumat ini disimpan dalam profil pesakit.",
    symptomsMedicineAllergiesSave = "Simpan Alahan",
    severityMild = "Ringan", severityModerate = "Sederhana", severityHigh = "Teruk", severityUnknown = "Tidak diketahui",

    factCheckTitle = "Semak Fakta",
    factCheckSubtitle = "Tampal mesej yang diteruskan atau taip dakwaan kesihatan untuk disahkan dengan sumber yang dipercayai.",
    factCheckLanguageLabel = "Bahasa", factCheckClaimLabel = "Dakwaan kesihatan",
    factCheckClaimPlaceholder = "cth. \"Menara 5G merebakkan COVID-19\"", factCheckSubmit = "Semak dakwaan ini",
    factCheckInstantMatch = "Padanan segera (cache tempatan)",
    factCheckNoOfficialSource = "⚠ Tiada sumber kerajaan Malaysia yang dipercayai ditemui untuk dakwaan ini — keputusan ini berdasarkan sumber web umum.",
    factCheckEvidenceSourceLabel = "Sumber Bukti:", factCheckEvidenceSourcesLabel = "Sumber Bukti:",
    factCheckViewSource = "Lihat sumber rasmi", factCheckFlagVerdict = "Tandakan keputusan ini",
    factCheckFlagged = "Dihantar untuk semakan doktor", factCheckEmptyClaimError = "Sila masukkan dakwaan untuk disemak.",
    factCheckServiceError = "Tidak dapat menghubungi perkhidmatan pengesahan. Sila semak sambungan anda dan cuba lagi.",
    factCheckVoiceUnavailable = "Input suara tidak tersedia pada peranti ini.",
    factCheckAllergyWarning = "⚠ Amaran Alahan: Ubat ini sepadan dengan ubat yang anda rekod sebagai alahan.",
    factCheckInteractionUnavailable = "Semakan interaksi ubat belum didayakan kerana tiada sumber interaksi yang disahkan dikonfigurasi. Tiada interaksi dibuat secara andaian.",
    verdictTrue = "BENAR", verdictFalse = "PALSU", verdictMisleading = "MENGELIRUKAN", verdictUnverified = "BELUM DISAHKAN",

    healthAssistantTitle = "Pembantu Kesihatan",
    healthAssistantSubtitle = "Panduan maklumat umum sahaja — bukan diagnosis.",
    healthAssistantSymptomsLabel = "Gejala", healthAssistantBloodPressureLabel = "Tekanan darah",
    healthAssistantTemperatureLabel = "Suhu badan", healthAssistantSubmit = "Dapatkan panduan",
    healthAssistantFlagResponse = "Tandakan respons ini", healthAssistantFlagged = "Dihantar untuk semakan doktor",

    medCoachTitle = "MedCoach", medCoachSubtitle = "Carian Maklumat Ubat FDA",
    medCoachSearchLabel = "Cari Ubat", medCoachSearchPlaceholder = "Masukkan Nama Ubat (cth. Panadol)",
    medCoachGetTip = "Dapatkan Petua AI Peribadi", medCoachThinking = "Jurulatih sedang berfikir...",
    medCoachViewHistory = "Lihat Sejarah", medCoachHistoryTitle = "Petua AI Terkini",
    medCoachNoHistory = "Tiada sejarah ditemui.",
    medCoachFdaLabelInfo = "Maklumat Label Rasmi FDA", medCoachPurpose = "Tujuan",
    medCoachWarnings = "Amaran Penting", medCoachAllergyWarning = "⚠ Amaran Alahan: Rekod pengambilan ubat anda mengandungi ubat yang sepadan dengan alahan yang direkodkan.", medCoachDosageAdmin = "Dos & Pentadbiran",
    medCoachIndications = "Indikasi & Penggunaan", readMore = "Baca Lagi...", showLess = "Tunjuk Kurang",

    settingsTitle = "Tetapan Akaun", settingsAccountSection = "Akaun", settingsNameLabel = "Nama: %s",
    settingsPhoneLabel = "Telefon: %s", settingsPatientIdLabel = "ID Pesakit: %s", settingsAgeLabel = "Umur: %s",
    settingsAgeFieldLabel = "Umur", settingsAgeNotSet = "Belum ditetapkan", settingsAgeSave = "Simpan Umur", settingsLanguageSection = "Bahasa",
    settingsFontSizeSection = "Saiz Fon", settingsFontSizeDefault = "Lalai", settingsFontSizeLarge = "Besar",
    settingsFontSizeExtraLarge = "Sangat Besar", settingsClinicianLogin = "Log Masuk Klinisian",
    settingsPreferencesSaved = "Keutamaan disimpan",

    historyTitle = "Sejarah", historySubtitle = "Penyerahan semakan fakta anda yang lalu.",
    historyEmpty = "Belum ada semakan fakta. Keputusan yang anda semak akan muncul di sini.",
    historyOriginalMessageLabel = "Mesej asal", historyResponseLabel = "Respons",
    historySourcesLabel = "Sumber"
)

fun stringsFor(language: AppLanguage): Strings = when (language) {
    AppLanguage.ENGLISH -> EnglishStrings
    AppLanguage.CHINESE -> ChineseStrings
    AppLanguage.BAHASA_MALAYSIA -> BahasaMalaysiaStrings
}

/** Provides the current patient's [Strings]. Defaults to English if never overridden (e.g. before login). */
val LocalStrings = staticCompositionLocalOf { EnglishStrings }
