package com.colleen.s36349879.medtrack.data.medication

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import com.colleen.s36349879.medtrack.data.patient.Patient

/**
 * Represents a medication record assigned to a specific patient in the database.
 *
 * This data class is annotated with [@Entity] to define it as a Room database table.
 * It includes a foreign key relationship with the [Patient] entity, ensuring that
 * when a patient is deleted, all their associated medications are automatically
 * removed via CASCADE.
 */
@Entity(
    tableName = "medication_table",
    foreignKeys = [ForeignKey(
            entity = Patient::class, // Links this table to the Patient table
            parentColumns = ["patientId"],
            childColumns = ["patientId"],
            onDelete = ForeignKey.CASCADE
    )]
)
data class Medication(

    /**
     * The unique identifier for this medication record.
     * Automatically generated by the database on insertion.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    val patientId: String,
    val medicationName: String,
    val dosage: String,
    val frequency: String,
    val medicationTime: String,
    val medicationType: String,
    val medicationNotes: String,
    val isTaken: Boolean = false,
    val lastTakenDate: String = ""
)
