package com.colleen.s36349879.medtrack.data.symptom

import androidx.room.Entity
import androidx.room.ForeignKey
import com.colleen.s36349879.medtrack.data.patient.Patient
import androidx.room.PrimaryKey

/**
 * Represents a symptom record logged by a patient in the local Room database.
 *
 * This data class is annotated with [@Entity] to define it as a Room database table.
 * It includes a foreign key relationship with the [Patient] entity, ensuring that
 * when a patient is deleted, all their associated symptoms are automatically
 * removed via CASCADE.
 */
@Entity(
    tableName = "symptom_table",
    foreignKeys = [ForeignKey(
        entity = Patient::class,
        parentColumns = ["patientId"],
        childColumns = ["patientId"],
        onDelete = ForeignKey.CASCADE
    )]
)
data class Symptom(
    /**
     * The unique identifier for this symptom record.
     * Automatically generated by the database on insertion.
     * Also used to determine insertion order in [SymptomDao.getRecentSeverities].
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    val patientId: String,
    val category: String,
    val severity: Int,
    val symptomNotes: String,
    val symptomDateTime: String
)
